[project]
name = "plant-disease-detection-gujarati"
version = "1.0.0"
description = "Plant Disease Detection in Gujarati"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.110.0",
    "uvicorn>=0.28.0",
    "python-multipart>=0.0.9",
    "pillow>=10.2.0",
    "numpy>=1.26.0",
    "onnxruntime>=1.17.0",
    "python-dotenv>=1.0.0",
    "requests>=2.31.0"
]

[tool.vercel]
entrypoint = "API.main:app"
